### ISSUE TITLE
Wheels on pypi.org

### ISSUE THREAD

**Issue by pawamoy** [c-w/ghp-import#101]
Could you provide wheels on pypi.org? I believe it's as easy as installing `wheel` in your dev environment and running `python setup.py bdist_wheel` to create the wheel. Then you can upload it using Twine, as usual.

**Comment by c-w** [comment]
Thanks for the pull request. I released [2.0.2](https://pypi.org/project/ghp-import/2.0.2/) which contains the [wheel](https://files.pythonhosted.org/packages/d5/42/a00220ae61d06b5bb288c0006bfd32bd61b4ae61adaef61fe8ad3a8ff9c3/ghp_import-2.0.2-py3-none-any.whl).
