### ISSUE TITLE
ident nonsense

### ISSUE THREAD

**Issue by Dragonlord1005** [c-w/ghp-import#104]
So whenever I run this, wether with another tool or by itself i get this error.
`fatal: Missing > in ident string: Dragonlord1005 <<>> 1637266254 +0000
fast-import: dumping crash report to .git/fast_import_crash_1954
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/bin/ghp-import", line 8, in <module>
    sys.exit(main())
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ghp_import.py", line 278, in main
    ghp_import(args[0], **opts.__dict__)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ghp_import.py", line 257, in ghp_import
    run_import(git, srcdir, **opts)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ghp_import.py", line 192, in run_import
    pipe.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by c-w** [comment]
Thanks for reaching out. What git version are you on? Does this happen with every repository or with some?

**Comment by Dragonlord1005** [comment]
I am running git 2.17.1 and it seems to happen with every repository, I am also unable to update git because I am using a coding sandbox site (replit) and they do not allow you to update git.

**Comment by c-w** [comment]
Given that it happens on every reposting, I’d assume it’s linked to the global git config. Could you share that here too?

**Comment by Dragonlord1005** [comment]
How would I do that? (Sorry, not super efficient in git itself.)

**Comment by c-w** [comment]
I believe `git config --list` should do the trick.

**Comment by Dragonlord1005** [comment]
core.excludesfile=/etc/.gitignore
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
user.name=Dragonlord1005
user.email=<>
remote.origin.url=https://github.com/Dragonlord1005/Nikola
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master

**Comment by c-w** [comment]
I would assume that `user.email=<>` could be causing the issue. Could you run `git config user.email you@domain.tld` and confirm whether the error persists?

**Comment by Dragonlord1005** [comment]
Thank you so much! That fixed it!
