### ISSUE TITLE
opt `--no-jekyll` should place `.nojekyll` under `--prefix` directory

### ISSUE THREAD

**Issue by achekerylla** [c-w/ghp-import#106]
## Summary

We would expect opt `--no-jekyll` should place `.nojekyll` in `gh-pages` branch under `--prefix` directory.  However, it instead places the file at the root directory.  GitHub Pages deployment seems to ignore the `.nojekyll` file unless it is exactly at the web serving directory (i.e. `/docs` in my case)

## Related source code section:

https://github.com/c-w/ghp-import/blob/5bf63c44f0a5aa22da4374c6cfb1c7c00d21eb61/ghp_import.py#L157-L160

## Commands:

``` bash
$ ghp-import --version
2.0.2

$  ghp-import \
    --no-jekyll \
    --push \
    --prefix=docs \
    --force \
    --no-history \
    ${BOOK_DIR}/_build/html
```

```bash
 $ git checkout gh-pages ; git pull ; cd $(git rev-parse --show-toplevel); find . -name .nojekyll
./.nojekyll
```

**Comment by achekerylla** [comment]
## Current workaround for user

```
  # https://github.com/c-w/ghp-import/issues/106
  # move .nojekyll under --prefix directory in gh-pages branch
  cd $(git rev-parse --show-toplevel) \
    && git add -A && git stash push \
    && git checkout gh-pages && git pull \
    && git mv ./.nojekyll ./docs/.nojekyll \
    && git commit -m "move .nojekyll file into place" && git push \
    && git checkout - && git stash pop
```

**Comment by c-w** [comment]
Good catch! Should be a fairly straight forward fix. Would you mind
submitting a pull request?

**Comment by achekerylla** [comment]
Posted https://github.com/c-w/ghp-import/pull/107
