### ISSUE TITLE
License the repository under an actual open source license

### ISSUE THREAD

**Issue by dhimmel** [c-w/ghp-import#71]
Currently, this repository is licensed under:

https://github.com/davisp/ghp-import/blob/0e2045e750569f67cbcd96e7e53dbfc865df747e/setup.py#L20

which reads:

https://github.com/davisp/ghp-import/blob/0e2045e750569f67cbcd96e7e53dbfc865df747e/LICENSE#L1-L11

Since ghp-import has a large user base that depends on it, I think it'd make sense to change the license to an actual open source license. Currently, for example, the lack of an open source license makes me less willing to contribute larger changes, since I don't want to spend time on something where there could be legal issues preventing future reuse.

I'd be happy to create a PR with a chosen license. I'd recommend MIT or BSD 3-Clause.

**Comment by c-w** [comment]
Unless @davisp objects, I plan to soon make a final release to `v0.6.0` under the current license and then re-release the project under [Apache 2.0](https://apache.org/licenses/LICENSE-2.0.html) as `v1.0.0`.

**Comment by c-w** [comment]
As of [v1.0.0](https://pypi.org/project/ghp-import/1.0.0/) the project is now licensed under the Apache 2.0 license.
