### ISSUE TITLE
Problem installing ghp-import into Gradle project

### ISSUE THREAD

**Issue by dcp65** [c-w/ghp-import#91]
I am using the[ gradle-use-python-plugin](https://github.com/xvik/gradle-use-python-plugin) to try to install ghp-import into a Gradle project. 

The project's `build.gradle` includes the following line:

`python.pip 'ghp-import:1.0.0'`

And when I run the plugin's `pipList` task, I see the following:

```
         Package         Version
	 --------------- -------
	 ghp-import      1.0.0
	 pip             20.2.4
	 python-dateutil 2.8.1
	 setuptools      50.3.2
	 six             1.15.0
	 wheel           0.35.1
```

So it looks like the install was successful. 

However, if I try to run the ghp_import module, I get the following:

`ModuleNotFoundError: No module named 'ghp_import'`

The Python install in the project includes the following under `site-packages`:

ghp_import-1.0.0.dist.info
ghp_import.py

**Comment by c-w** [comment]
Could you share a gradlefile and command sequence that reproduces the issue?

**Comment by dcp65** [comment]
My apologies, I was doing it wrong.

For the record, here is the project:

https://github.com/dcp65/swagger-asciidoc-primer
