### ISSUE TITLE
Problem adding file with CJK punctuation

### ISSUE THREAD

**Issue by Weilet** [c-w/ghp-import#92]
[Pelican](https://blog.getpelican.com) uses ghp-import to publish blog articles to GitHub page, but I found it would throw out FileNotFoundError when the article used  CJK punctuation because this [method](https://github.com/c-w/ghp-import/blob/ea73ce7e1fc49d6cbf84ded7428489f53a6d88ff/ghp_import.py#L122) would change `，` into `,`.

I also found that this method is to solve this [problem](https://stackoverflow.com/questions/5581857/git-and-the-umlaut-problem-on-mac-os-x/5582439#5582439) which already fixed by git. So I think we can remove this method.

**Comment by c-w** [comment]
Thanks for reporting this. Looking into it.

**Comment by c-w** [comment]
@Weilet I believe I have a fix for this. Could you please run your scenario using [ghp_import.py at 3f25f9c](https://github.com/c-w/ghp-import/blob/3f25f9c9613286d7b0e303a79e8db4c0b523419d/ghp_import.py) and verify that everything works as expected?

**Comment by Weilet** [comment]
@c-w Problem fixed, thx!

**Comment by c-w** [comment]
Released in [v1.0.1](https://pypi.org/project/ghp-import/1.0.1/)
