### ISSUE TITLE
ghp-import with two users?

### ISSUE THREAD

**Issue by cooperrc** [c-w/ghp-import#94]
I don't think this is an issue with `ghp-import`, but I want to know if there is preferred workflow for collaborators updating a github-pages site:

__Use case__:

1. I use `ghp-import -n -f -p _build/html` to send updated html to github-pages
2. Collaborator updates source files and builds html
3. Collaborator uses `ghp-import -n -f -p _build/html`, but receives error

Is there a better workflow?

**Comment by c-w** [comment]
I believe the authorization context is inherited from the environment, so if the collaborator has write access to the repository they should be able to use `ghp-import` to publish the files. Could you provide some more context on exactly how you're setting up the integration so that I can provide a more in-depth response.

**Comment by cooperrc** [comment]
I'll have to check the collaborator write access settings. That might be the problem. 

> Could you provide some more context on exactly how you're setting up the integration so that I can provide a more in-depth response.

In the current situation, we are collaborating using [Jupyter Book](https://jupyterbook.org/intro.html) to build our github-pages site. Each of use will create notebooks, build the site, then push changes to a repository. We use `ghp-import` to push the html build to github.

**Comment by cooperrc** [comment]
Is there a setting to change for a collaborator in Github that allows `ghp-import` access? It seems like once someone is a collaborator, they have access to the whole repo. 

This may be more of a github FAQ now, but I'm not sure how `ghp-import` interacts with the github permissions.

**Comment by c-w** [comment]
`ghp-import` inherits the permissions of the user that's executing the script so this really is more of a Github question. If you're on Github Team or Enterprise, I believe you could use the "[Restrict who can push to matching branches](https://docs.github.com/en/github/administering-a-repository/about-protected-branches#restrict-who-can-push-to-matching-branches)" feature to manage write access to the `gh-pages` branch. Not sure about how to best achieve this effect on the free tier, except perhaps protecting all branches except for `gh-pages` to require pull request reviews before push?

**Comment by cooperrc** [comment]
Thanks @c-w, I think you're right its a GitHub issue at this point. 

I had not created any restrictions for contributing to the `gh-pages` branch, so it may be a different issue with how we managed our workflow. 

I'll close the issue and try to nail down where the issue might have been for future users.
